import type { MysterySet } from "@/lib/rosary/types";

export const joyfulMysteries: MysterySet = {
  id: "joyful",
  title: "Joyful Mysteries",
  traditionalDays: "Monday and Saturday",
  mysteries: [
    {
      id: "annunciation",
      setId: "joyful",
      setName: "Joyful Mysteries",
      title: "The Annunciation",
      number: 1,
      description: "The angel Gabriel announces to Mary that she will bear the Son of God.",
      scriptureReference: "Luke 1:26-38",
      fruitOfMystery: "Humility",
      shortLabel: "Annunciation",
    },
    {
      id: "visitation",
      setId: "joyful",
      setName: "Joyful Mysteries",
      title: "The Visitation",
      number: 2,
      description: "Mary visits Elizabeth, and Elizabeth rejoices at the presence of the Lord.",
      scriptureReference: "Luke 1:39-56",
      fruitOfMystery: "Love of neighbor",
      shortLabel: "Visitation",
    },
    {
      id: "nativity",
      setId: "joyful",
      setName: "Joyful Mysteries",
      title: "The Nativity",
      number: 3,
      description: "Jesus is born in Bethlehem and laid in a manger.",
      scriptureReference: "Luke 2:1-20",
      fruitOfMystery: "Poverty of spirit",
      shortLabel: "Nativity",
    },
    {
      id: "presentation",
      setId: "joyful",
      setName: "Joyful Mysteries",
      title: "The Presentation",
      number: 4,
      description: "Mary and Joseph present Jesus in the temple.",
      scriptureReference: "Luke 2:22-38",
      fruitOfMystery: "Obedience",
      shortLabel: "Presentation",
    },
    {
      id: "finding-in-temple",
      setId: "joyful",
      setName: "Joyful Mysteries",
      title: "The Finding of Jesus in the Temple",
      number: 5,
      description: "Mary and Joseph find the young Jesus teaching in his Father's house.",
      scriptureReference: "Luke 2:41-52",
      fruitOfMystery: "Joy in finding Jesus",
      shortLabel: "Finding in the Temple",
    },
  ],
};

export const luminousMysteries: MysterySet = {
  id: "luminous",
  title: "Luminous Mysteries",
  traditionalDays: "Thursday",
  mysteries: [
    {
      id: "baptism",
      setId: "luminous",
      setName: "Luminous Mysteries",
      title: "The Baptism of Jesus",
      number: 1,
      description: "Jesus is baptized in the Jordan, and the Father's voice is heard.",
      scriptureReference: "Matthew 3:13-17",
      fruitOfMystery: "Openness to the Holy Spirit",
      shortLabel: "Baptism",
    },
    {
      id: "wedding-at-cana",
      setId: "luminous",
      setName: "Luminous Mysteries",
      title: "The Wedding at Cana",
      number: 2,
      description: "Jesus performs his first public sign at Mary's request.",
      scriptureReference: "John 2:1-12",
      fruitOfMystery: "To Jesus through Mary",
      shortLabel: "Cana",
    },
    {
      id: "proclamation",
      setId: "luminous",
      setName: "Luminous Mysteries",
      title: "The Proclamation of the Kingdom",
      number: 3,
      description: "Jesus calls all people to repentance and faith in the Gospel.",
      scriptureReference: "Mark 1:14-15",
      fruitOfMystery: "Conversion",
      shortLabel: "Kingdom",
    },
    {
      id: "transfiguration",
      setId: "luminous",
      setName: "Luminous Mysteries",
      title: "The Transfiguration",
      number: 4,
      description: "Jesus is revealed in glory before Peter, James, and John.",
      scriptureReference: "Matthew 17:1-8",
      fruitOfMystery: "Desire for holiness",
      shortLabel: "Transfiguration",
    },
    {
      id: "eucharist",
      setId: "luminous",
      setName: "Luminous Mysteries",
      title: "The Institution of the Eucharist",
      number: 5,
      description: "Jesus gives his Body and Blood at the Last Supper.",
      scriptureReference: "Luke 22:14-20",
      fruitOfMystery: "Love of the Eucharist",
      shortLabel: "Eucharist",
    },
  ],
};

export const sorrowfulMysteries: MysterySet = {
  id: "sorrowful",
  title: "Sorrowful Mysteries",
  traditionalDays: "Tuesday and Friday",
  mysteries: [
    {
      id: "agony-in-garden",
      setId: "sorrowful",
      setName: "Sorrowful Mysteries",
      title: "The Agony in the Garden",
      number: 1,
      description: "Jesus prays in sorrow and obedience before his Passion.",
      scriptureReference: "Luke 22:39-46",
      fruitOfMystery: "Sorrow for sin",
      shortLabel: "Agony",
    },
    {
      id: "scourging",
      setId: "sorrowful",
      setName: "Sorrowful Mysteries",
      title: "The Scourging at the Pillar",
      number: 2,
      description: "Jesus is scourged and suffers for the sins of the world.",
      scriptureReference: "John 19:1",
      fruitOfMystery: "Purity",
      shortLabel: "Scourging",
    },
    {
      id: "crowning-thorns",
      setId: "sorrowful",
      setName: "Sorrowful Mysteries",
      title: "The Crowning with Thorns",
      number: 3,
      description: "Jesus is mocked as king and crowned with thorns.",
      scriptureReference: "Matthew 27:27-31",
      fruitOfMystery: "Moral courage",
      shortLabel: "Crowning",
    },
    {
      id: "carrying-cross",
      setId: "sorrowful",
      setName: "Sorrowful Mysteries",
      title: "The Carrying of the Cross",
      number: 4,
      description: "Jesus carries the cross to Calvary.",
      scriptureReference: "John 19:16-17",
      fruitOfMystery: "Patience",
      shortLabel: "Carrying the Cross",
    },
    {
      id: "crucifixion",
      setId: "sorrowful",
      setName: "Sorrowful Mysteries",
      title: "The Crucifixion",
      number: 5,
      description: "Jesus dies on the cross for our salvation.",
      scriptureReference: "Luke 23:44-49",
      fruitOfMystery: "Perseverance",
      shortLabel: "Crucifixion",
    },
  ],
};

export const gloriousMysteries: MysterySet = {
  id: "glorious",
  title: "Glorious Mysteries",
  traditionalDays: "Wednesday and Sunday",
  mysteries: [
    {
      id: "resurrection",
      setId: "glorious",
      setName: "Glorious Mysteries",
      title: "The Resurrection",
      number: 1,
      description: "Jesus rises from the dead in victory over sin and death.",
      scriptureReference: "Matthew 28:1-10",
      fruitOfMystery: "Faith",
      shortLabel: "Resurrection",
    },
    {
      id: "ascension",
      setId: "glorious",
      setName: "Glorious Mysteries",
      title: "The Ascension",
      number: 2,
      description: "Jesus ascends to the Father and commissions his disciples.",
      scriptureReference: "Acts 1:6-11",
      fruitOfMystery: "Hope",
      shortLabel: "Ascension",
    },
    {
      id: "descent-holy-spirit",
      setId: "glorious",
      setName: "Glorious Mysteries",
      title: "The Descent of the Holy Spirit",
      number: 3,
      description: "The Holy Spirit descends upon Mary and the apostles at Pentecost.",
      scriptureReference: "Acts 2:1-13",
      fruitOfMystery: "Love of God",
      shortLabel: "Pentecost",
    },
    {
      id: "assumption",
      setId: "glorious",
      setName: "Glorious Mysteries",
      title: "The Assumption of Mary",
      number: 4,
      description: "Mary is taken body and soul into heavenly glory.",
      fruitOfMystery: "Grace of a happy death",
      shortLabel: "Assumption",
    },
    {
      id: "coronation",
      setId: "glorious",
      setName: "Glorious Mysteries",
      title: "The Coronation of Mary",
      number: 5,
      description: "Mary is crowned Queen of Heaven and Earth.",
      fruitOfMystery: "Trust in Mary's intercession",
      shortLabel: "Coronation",
    },
  ],
};

export const mysterySets: MysterySet[] = [
  joyfulMysteries,
  luminousMysteries,
  sorrowfulMysteries,
  gloriousMysteries,
];

export const mysterySetsById = Object.fromEntries(
  mysterySets.map((set) => [set.id, set]),
) as Record<MysterySet["id"], MysterySet>;

export const mysteriesById = Object.fromEntries(
  mysterySets.flatMap((set) => set.mysteries.map((mystery) => [mystery.id, mystery])),
) as Record<string, MysterySet["mysteries"][number]>;
