import type { Prayer } from "@/lib/rosary/types";

export const prayers: Prayer[] = [
  {
    id: "sign-of-the-cross",
    title: "Sign of the Cross",
    incipit: "In the name of the Father...",
    text: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
    shortText: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
    category: "opening",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Sign of the Cross",
        incipit: "In the name of the Father...",
        text: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
        shortText: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
      },
      la: {
        language: "la",
        title: "Signum Crucis",
        incipit: "In nomine Patris...",
        text: "In nomine Patris, et Filii, et Spiritus Sancti. Amen.",
        shortText: "In nomine Patris, et Filii, et Spiritus Sancti. Amen.",
      },
      es: {
        language: "es",
        title: "Señal de la Cruz",
        incipit: "En el nombre del Padre...",
        text: "En el nombre del Padre, y del Hijo, y del Espíritu Santo. Amén.",
        shortText: "En el nombre del Padre, y del Hijo, y del Espíritu Santo. Amén.",
      },
    },
  },
  {
    id: "apostles-creed",
    title: "Apostles' Creed",
    incipit: "I believe in God...",
    text: "I believe in God, the Father almighty, Creator of heaven and earth, and in Jesus Christ, his only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died and was buried; he descended into hell; on the third day he rose again from the dead; he ascended into heaven, and is seated at the right hand of God the Father almighty; from there he will come to judge the living and the dead.\n\nI believe in the Holy Spirit, the holy catholic Church, the communion of saints, the forgiveness of sins, the resurrection of the body, and life everlasting. Amen.",
    shortText: "I believe in God, the Father almighty, Creator of heaven and earth...",
    category: "opening",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Apostles' Creed",
        incipit: "I believe in God...",
        text: "I believe in God, the Father almighty, Creator of heaven and earth, and in Jesus Christ, his only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died and was buried; he descended into hell; on the third day he rose again from the dead; he ascended into heaven, and is seated at the right hand of God the Father almighty; from there he will come to judge the living and the dead.\n\nI believe in the Holy Spirit, the holy catholic Church, the communion of saints, the forgiveness of sins, the resurrection of the body, and life everlasting. Amen.",
        shortText: "I believe in God, the Father almighty, Creator of heaven and earth...",
      },
      la: {
        language: "la",
        title: "Symbolum Apostolorum",
        incipit: "Credo in Deum...",
        text: "Credo in Deum, Patrem omnipotentem, Creatorem caeli et terrae; et in Iesum Christum, Filium eius unicum, Dominum nostrum; qui conceptus est de Spiritu Sancto, natus ex Maria Virgine, passus sub Pontio Pilato, crucifixus, mortuus, et sepultus; descendit ad inferos; tertia die resurrexit a mortuis; ascendit ad caelos, sedet ad dexteram Dei Patris omnipotentis; inde venturus est iudicare vivos et mortuos.\n\nCredo in Spiritum Sanctum, sanctam Ecclesiam catholicam, sanctorum communionem, remissionem peccatorum, carnis resurrectionem, vitam aeternam. Amen.",
        shortText: "Credo in Deum, Patrem omnipotentem, Creatorem caeli et terrae...",
      },
      es: {
        language: "es",
        title: "Credo de los Apóstoles",
        incipit: "Creo en Dios...",
        text: "Creo en Dios, Padre todopoderoso, Creador del cielo y de la tierra.\n\nCreo en Jesucristo, su único Hijo, nuestro Señor, que fue concebido por obra y gracia del Espíritu Santo, nació de Santa María Virgen; padeció bajo el poder de Poncio Pilato; fue crucificado, muerto y sepultado; descendió a los infiernos; al tercer día resucitó de entre los muertos; subió a los cielos y está sentado a la derecha de Dios Padre todopoderoso. Desde allí ha de venir a juzgar a vivos y muertos.\n\nCreo en el Espíritu Santo, la santa Iglesia católica, la comunión de los santos, el perdón de los pecados, la resurrección de la carne y la vida eterna. Amén.",
        shortText: "Creo en Dios...",
      },
    },
  },
  {
    id: "our-father",
    title: "Our Father",
    incipit: "Our Father...",
    text: "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven.\n\nGive us this day our daily bread; and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.",
    shortText: "Our Father...",
    category: "decade",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Our Father",
        incipit: "Our Father...",
        text: "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven.\n\nGive us this day our daily bread; and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.",
        shortText: "Our Father...",
      },
      la: {
        language: "la",
        title: "Pater Noster",
        incipit: "Pater noster...",
        text: "Pater noster, qui es in caelis, sanctificetur nomen tuum; adveniat regnum tuum; fiat voluntas tua, sicut in caelo et in terra.\n\nPanem nostrum quotidianum da nobis hodie; et dimitte nobis debita nostra, sicut et nos dimittimus debitoribus nostris; et ne nos inducas in tentationem; sed libera nos a malo. Amen.",
        shortText: "Pater noster...",
      },
      es: {
        language: "es",
        title: "Padre Nuestro",
        incipit: "Padre nuestro...",
        text: "Padre nuestro, que estás en el cielo, santificado sea tu Nombre; venga a nosotros tu reino; hágase tu voluntad en la tierra como en el cielo.\n\nDanos hoy nuestro pan de cada día; perdona nuestras ofensas, como también nosotros perdonamos a los que nos ofenden; no nos dejes caer en la tentación, y líbranos del mal. Amén.",
        shortText: "Padre nuestro...",
      },
    },
  },
  {
    id: "hail-mary",
    title: "Hail Mary",
    incipit: "Hail Mary...",
    text: "Hail Mary, full of grace, the Lord is with thee; blessed art thou among women, and blessed is the fruit of thy womb, Jesus.\n\nHoly Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.",
    shortText: "Hail Mary...",
    category: "decade",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Hail Mary",
        incipit: "Hail Mary...",
        text: "Hail Mary, full of grace, the Lord is with thee; blessed art thou among women, and blessed is the fruit of thy womb, Jesus.\n\nHoly Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.",
        shortText: "Hail Mary...",
      },
      la: {
        language: "la",
        title: "Ave Maria",
        incipit: "Ave Maria...",
        text: "Ave Maria, gratia plena, Dominus tecum; benedicta tu in mulieribus, et benedictus fructus ventris tui, Iesus.\n\nSancta Maria, Mater Dei, ora pro nobis peccatoribus, nunc et in hora mortis nostrae. Amen.",
        shortText: "Ave Maria, gratia plena...",
      },
      es: {
        language: "es",
        title: "Ave María",
        incipit: "Dios te salve, María...",
        text: "Dios te salve, María, llena eres de gracia; el Señor es contigo. Bendita tú eres entre todas las mujeres, y bendito es el fruto de tu vientre, Jesús.\n\nSanta María, Madre de Dios, ruega por nosotros, pecadores, ahora y en la hora de nuestra muerte. Amén.",
        shortText: "Dios te salve, María...",
      },
    },
  },
  {
    id: "glory-be",
    title: "Glory Be",
    incipit: "Glory be...",
    text: "Glory be to the Father, and to the Son, and to the Holy Spirit.\n\nAs it was in the beginning, is now, and ever shall be, world without end. Amen.",
    shortText: "Glory be...",
    category: "decade",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Glory Be",
        incipit: "Glory be...",
        text: "Glory be to the Father, and to the Son, and to the Holy Spirit.\n\nAs it was in the beginning, is now, and ever shall be, world without end. Amen.",
        shortText: "Glory be...",
      },
      la: {
        language: "la",
        title: "Gloria Patri",
        incipit: "Gloria Patri...",
        text: "Gloria Patri, et Filio, et Spiritui Sancto.\n\nSicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen.",
        shortText: "Gloria Patri...",
      },
      es: {
        language: "es",
        title: "Gloria",
        incipit: "Gloria al Padre...",
        text: "Gloria al Padre, y al Hijo, y al Espíritu Santo.\n\nComo era en el principio, ahora y siempre, por los siglos de los siglos. Amén.",
        shortText: "Gloria al Padre...",
      },
    },
  },
  {
    id: "fatima-prayer",
    title: "Fatima Prayer",
    incipit: "O my Jesus...",
    text: "O my Jesus, forgive us our sins, save us from the fires of hell, lead all souls to heaven, especially those in most need of thy mercy. Amen.",
    shortText: "O my Jesus...",
    category: "decade",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Fatima Prayer",
        incipit: "O my Jesus...",
        text: "O my Jesus, forgive us our sins, save us from the fires of hell, lead all souls to heaven, especially those in most need of thy mercy. Amen.",
        shortText: "O my Jesus...",
      },
      la: {
        language: "la",
        title: "Oratio Fatimae",
        incipit: "O mi Iesu...",
        text: "O mi Iesu, dimitte nobis debita nostra, libera nos ab igne inferni, perduc in caelum omnes animas, praesertim eas quae misericordiae tuae maxime indigent.",
        shortText: "O mi Iesu...",
      },
      es: {
        language: "es",
        title: "Oración de Fátima",
        incipit: "Oh Jesús mío...",
        text: "Oh Jesús mío, perdona nuestros pecados, líbranos del fuego del infierno, lleva al cielo a todas las almas, especialmente a las más necesitadas de tu misericordia.",
        shortText: "Oh Jesús mío...",
      },
    },
  },
  {
    id: "hail-holy-queen",
    title: "Hail Holy Queen",
    incipit: "Hail, holy Queen, Mother of mercy...",
    text: "Hail, holy Queen, Mother of mercy, our life, our sweetness, and our hope. To thee do we cry, poor banished children of Eve; to thee do we send up our sighs, mourning and weeping in this valley of tears.\n\nTurn then, most gracious advocate, thine eyes of mercy toward us; and after this our exile, show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary.",
    shortText: "Hail, holy Queen, Mother of mercy...",
    category: "closing",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Hail Holy Queen",
        incipit: "Hail, holy Queen, Mother of mercy...",
        text: "Hail, holy Queen, Mother of mercy, our life, our sweetness, and our hope. To thee do we cry, poor banished children of Eve; to thee do we send up our sighs, mourning and weeping in this valley of tears.\n\nTurn then, most gracious advocate, thine eyes of mercy toward us; and after this our exile, show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary.",
        shortText: "Hail, holy Queen, Mother of mercy...",
      },
      la: {
        language: "la",
        title: "Salve Regina",
        incipit: "Salve Regina...",
        text: "Salve Regina, Mater misericordiae; vita, dulcedo, et spes nostra, salve.\n\nAd te clamamus, exsules filii Hevae. Ad te suspiramus, gementes et flentes in hac lacrimarum valle.\n\nEia ergo, advocata nostra, illos tuos misericordes oculos ad nos converte.\n\nEt Iesum, benedictum fructum ventris tui, nobis post hoc exsilium ostende.\n\nO clemens, O pia, O dulcis Virgo Maria.\n\nOra pro nobis, sancta Dei Genitrix.\n\nUt digni efficiamur promissionibus Christi.",
        shortText: "Salve Regina...",
      },
      es: {
        language: "es",
        title: "Salve",
        incipit: "Dios te salve, Reina...",
        text: "Dios te salve, Reina y Madre de misericordia, vida, dulzura y esperanza nuestra; Dios te salve.\n\nA ti clamamos los desterrados hijos de Eva; a ti suspiramos, gimiendo y llorando en este valle de lágrimas.\n\nEa, pues, Señora, abogada nuestra, vuelve a nosotros esos tus ojos misericordiosos.\n\nY después de este destierro, muéstranos a Jesús, fruto bendito de tu vientre.\n\nOh clemente, oh piadosa, oh dulce Virgen María.\n\nRuega por nosotros, Santa Madre de Dios.\n\nPara que seamos dignos de alcanzar las promesas de nuestro Señor Jesucristo.",
        shortText: "Dios te salve, Reina...",
      },
    },
  },
  {
    id: "closing-prayer",
    title: "Closing Prayer",
    incipit: "O God, whose Only Begotten Son...",
    text: "O God, whose only begotten Son, by his life, death, and resurrection, has purchased for us the rewards of eternal life, grant, we beseech thee, that while meditating on these mysteries of the most holy Rosary of the Blessed Virgin Mary, we may imitate what they contain and obtain what they promise, through the same Christ our Lord. Amen.",
    shortText: "O God, whose Only Begotten Son...",
    category: "closing",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Closing Prayer",
        incipit: "O God, whose Only Begotten Son...",
        text: "O God, whose only begotten Son, by his life, death, and resurrection, has purchased for us the rewards of eternal life, grant, we beseech thee, that while meditating on these mysteries of the most holy Rosary of the Blessed Virgin Mary, we may imitate what they contain and obtain what they promise, through the same Christ our Lord. Amen.",
        shortText: "O God, whose Only Begotten Son...",
      },
      la: {
        language: "la",
        title: "Oratio Conclusiva Rosarii",
        incipit: "Deus, cuius Unigenitus...",
        text: "Oremus.\n\nDeus, cuius Unigenitus per vitam, mortem et resurrectionem suam nobis salutis aeternae praemia comparavit: concede, quaesumus; ut haec mysteria sacratissimo beatae Mariae Virginis Rosario recolentes, et imitemur quod continent, et quod promittunt assequamur.\n\nPer eundem Christum Dominum nostrum. Amen.",
        shortText: "Deus, cuius Unigenitus...",
      },
      es: {
        language: "es",
        title: "Oración final del Rosario",
        incipit: "Oh Dios, cuyo unigénito Hijo...",
        text: "Oremos.\n\nOh Dios, cuyo unigénito Hijo, por su vida, muerte y resurrección, nos alcanzó el premio de la vida eterna: concédenos, te rogamos, que meditando estos misterios del santísimo Rosario de la bienaventurada Virgen María, imitemos lo que contienen y obtengamos lo que prometen.\n\nPor el mismo Jesucristo, nuestro Señor. Amén.",
        shortText: "Oh Dios, cuyo unigénito Hijo...",
      },
    },
  },
  {
    id: "memorare",
    title: "Memorare",
    incipit: "Remember, O most gracious Virgin Mary...",
    text: "Remember, O most gracious Virgin Mary, that never was it known that anyone who fled to thy protection, implored thy help, or sought thine intercession was left unaided.\n\nInspired by this confidence, I fly unto thee, O Virgin of virgins, my Mother. To thee do I come, before thee I stand, sinful and sorrowful. O Mother of the Word Incarnate, despise not my petitions, but in thy mercy hear and answer me. Amen.",
    shortText: "Remember, O most gracious Virgin Mary...",
    category: "optional",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "Memorare",
        incipit: "Remember, O most gracious Virgin Mary...",
        text: "Remember, O most gracious Virgin Mary, that never was it known that anyone who fled to thy protection, implored thy help, or sought thine intercession was left unaided.\n\nInspired by this confidence, I fly unto thee, O Virgin of virgins, my Mother. To thee do I come, before thee I stand, sinful and sorrowful. O Mother of the Word Incarnate, despise not my petitions, but in thy mercy hear and answer me. Amen.",
        shortText: "Remember, O most gracious Virgin Mary...",
      },
      la: {
        language: "la",
        title: "Memorare",
        incipit: "Memorare, O piissima Virgo Maria...",
        text: "Memorare, O piissima Virgo Maria, non esse auditum a saeculo quemquam ad tua currentem praesidia, tua implorantem auxilia, tua petentem suffragia esse derelictum.\n\nEgo tali animatus confidentia, ad te, Virgo Virginum, Mater, curro; ad te venio; coram te gemens peccator assisto.\n\nNoli, Mater Verbi, verba mea despicere; sed audi propitia et exaudi. Amen.",
        shortText: "Memorare, O piissima Virgo Maria...",
      },
      es: {
        language: "es",
        title: "Acordaos",
        incipit: "Acordaos, oh piadosísima Virgen María...",
        text: "Acordaos, oh piadosísima Virgen María, que jamás se ha oído decir que ninguno de los que han acudido a vuestra protección, implorando vuestra asistencia y reclamando vuestro socorro, haya sido desamparado.\n\nAnimado con esta confianza, a vos también acudo, oh Virgen, Madre de las vírgenes; y aunque gimiendo bajo el peso de mis pecados, me atrevo a comparecer ante vuestra presencia soberana.\n\nNo desechéis mis súplicas, oh Madre del Verbo divino; antes bien escuchadlas y acogedlas benignamente. Amén.",
        shortText: "Acordaos, oh piadosísima Virgen María...",
      },
    },
  },
  {
    id: "st-michael-prayer",
    title: "St. Michael Prayer",
    incipit: "St. Michael the Archangel...",
    text: "St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil.\n\nMay God rebuke him, we humbly pray, and do thou, O Prince of the heavenly hosts, by the power of God, cast into hell Satan, and all the evil spirits, who prowl about the world seeking the ruin of souls. Amen.",
    shortText: "St. Michael the Archangel...",
    category: "optional",
    defaultLanguage: "en",
    variants: {
      en: {
        language: "en",
        title: "St. Michael Prayer",
        incipit: "St. Michael the Archangel...",
        text: "St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil.\n\nMay God rebuke him, we humbly pray, and do thou, O Prince of the heavenly hosts, by the power of God, cast into hell Satan, and all the evil spirits, who prowl about the world seeking the ruin of souls. Amen.",
        shortText: "St. Michael the Archangel...",
      },
      la: {
        language: "la",
        title: "Sancte Michael Archangele",
        incipit: "Sancte Michael Archangele...",
        text: "Sancte Michael Archangele, defende nos in proelio; contra nequitiam et insidias diaboli esto praesidium.\n\nImperet illi Deus, supplices deprecamur: tuque, Princeps militiae caelestis, Satanam aliosque spiritus malignos, qui ad perditionem animarum pervagantur in mundo, divina virtute in infernum detrude. Amen.",
        shortText: "Sancte Michael Archangele...",
      },
      es: {
        language: "es",
        title: "San Miguel Arcángel",
        incipit: "San Miguel Arcángel...",
        text: "San Miguel Arcángel, defiéndenos en la batalla. Sé nuestro amparo contra la perversidad y acechanzas del demonio.\n\nReprímale Dios, pedimos suplicantes, y tú, Príncipe de la milicia celestial, arroja al infierno con el divino poder a Satanás y a los otros espíritus malignos que andan dispersos por el mundo para la perdición de las almas. Amén.",
        shortText: "San Miguel Arcángel...",
      },
    },
  },
];

export const prayersById = Object.fromEntries(
  prayers.map((prayer) => [prayer.id, prayer]),
) as Record<Prayer["id"], Prayer>;
